name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build Windows binary
      run: dotnet publish --runtime win-x64 --configuration Release --self-contained
    - name: Build Linux binary (full)
      run: dotnet publish --runtime linux-x64 --configuration Release --self-contained
    - name: Build Linux binary (musl)
      run: dotnet publish --runtime linux-musl-x64 --configuration Release --self-contained
